version: "3.3"

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=todos
            - POSTGRES_USER=angel
            - POSTGRES_PASSWORD=angel1234
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
